language: php
dist: xenial

php:
  - 7.3
  - 7.4

services:
  - mysql

before_install:
 - mysql -e 'CREATE DATABASE db_default;'
 - mysql db_default < ./config/sql/database.sql;
 - mysql -e 'CREATE DATABASE db_test;'
  
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --optimize-autoloader
  - cp ./config/travis/app_custom.php ./config/app_custom.php
  - bash ./bin/cake migrations migrate
  - npm --prefix ./webroot install ./webroot
  
script:
  - vendor/bin/phpstan analyze -c phpstan.neon --no-interaction --no-progress
  - vendor/bin/phpunit --filter testAddWorkshop --stderr
  - cat logs/cli-error.log && cat logs/cli-debug && cat logs/error.log && cat logs/debug.log
  
notifications:
  email: false
