language: php
dist: xenial

php:
  - 7.3

services:
  - mysql

before_install:
 - mysql -e 'CREATE DATABASE db_default;'
 - mysql db_default < ./config/sql/database.sql;
 - mysql -e 'CREATE DATABASE db_test;'
 - mysql -e 'SET GLOBAL sql_mode = "NO_ENGINE_SUBSTITUTION";'

before_script:
  # START email mock
  - sudo apt-get install -y -qq postfix  
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini
  # END email mock
  - composer install --optimize-autoloader
  - cp ./config/travis/app_custom.php ./config/app_custom.php
  - bash ./bin/cake migrations migrate
  - npm --prefix ./webroot install ./webroot
  
script:
  - vendor/bin/phpstan analyze -c phpstan.neon --no-interaction --no-progress
  - vendor/bin/phpunit --stderr
  
notifications:
  email: false
