language: php
dist: xenial
sudo: required

php:
  - 7.3

services:
  - mysql

before_install:
 - mysql -e CREATE DATABASE db_default;
 - mysql db_default < ./config/sql/database.sql;
 - mysql -e CREATE DATABASE db_test;

before_script:
  - composer install --optimize-autoloader
  - cp ./config/travis/app_custom.php ./config/app_custom.php
  - bash ./bin/cake migrations migrate
  
script:
  - vendor/bin/phpstan analyze -c phpstan.neon --no-interaction --no-progress
  - vendor/bin/phpunit --stderr
  
notifications:
  email: false
